### ISSUE TITLE
Plans for 2014

### ISSUE THREAD

**Issue by Mark-H** [phpwomen/sf2-phpwomen#6]
While browsing the website (got there from the elephpants!) I noticed the website seems to talk about 2014 a lot... It sounds to me (as an outsider) that most of it, like the initiatives and user groups, are still accurate, except that the year should probably be updated. 

I'm not familiar with how the site is set up with Symfony 2, but figured I could at least open an issue..

**Comment by lineke** [comment]
The year is updated now. So I am closing this issue. Thanks for the report @Mark-H
